openapi: 3.0.0
info:
  title: IBAN Validation API
  version: 1.0.0
  description: A simple API to register, authenticate, and validate IBANs.
servers:
  - url: http://localhost:3000/api
paths:
  /ibanvalidation:
    get:
      summary: Validate an IBAN
      parameters:
        - name: iban
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: IBAN validation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  iban:
                    type: string
                  valid:
                    type: boolean
                  country_code:
                    type: string
                  country_name:
                    type: string
        400:
          description: Missing or invalid IBAN parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  iban:
                    type: string
      security:
        - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
